### ISSUE TITLE
Swappy does not work

### ISSUE THREAD

**Issue by lw64** [Variable-ind/Pixelorama-Extensions#13]
I cannot add the extension after downloading it. The entry doesn't appear, so I also cannot activate it.

**Comment by Variable-ind** [comment]
Hy, you may be trying to download the version meant for pixelorama 1.0
For pixelorama 0.11.4 use this one https://github.com/Variable-ind/Pixelorama-Extensions/raw/3.x/Extensions/Swappy.pck

Are you trying to download the extension manually or through the [VariableStore](https://variable-interactive.itch.io/pixelorama-extensions)?

**Comment by lw64** [comment]
Oh right, I used the 4.0 branch, thanks for the quick reply :)
Somehow the variableStore extension worked though...
By the way is it worth to try out the 4.0 version of Pixelorama?

**Comment by Variable-ind** [comment]
> Oh right, I used the 4.0 branch, thanks for the quick reply :) Somehow the variableStore extension worked though... By the way is it worth to try out the 4.0 version of Pixelorama?

Yeah it's definitely worth it. It's still being developed though but you can try it out if you want. It has many (and i mean MANY) new features.

Note: it will also have a steam version (which is paid) but it's this way only to support the developers, and you can still get that same version completely free from your usual place (i mean from itch.io).

**Comment by lw64** [comment]
Is there a flathub-beta release planned? :D

**Comment by lw64** [comment]
master seems work great! :) Is there a list of new features somewhere?

**Comment by Variable-ind** [comment]
> master seems work great! :) Is there a list of new features somewhere?

Here you go
## changelog of pixelorama:
https://github.com/Orama-Interactive/Pixelorama/blob/master/CHANGELOG.md#v10---unreleased

## Latest nightly build download:
https://nightly.link/Orama-Interactive/Pixelorama/workflows/dev-desktop-builds/master
