### ISSUE TITLE
[store] doesnt see anything in store?

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [Variable-ind/Pixelorama-Extensions#16]
yes, just this : 
![image](https://user-images.githubusercontent.com/97974194/187953071-8891edea-e68e-4e3c-b3ef-c54dc14543d2.png)
![image](https://user-images.githubusercontent.com/97974194/187953233-726e33ac-9fdf-4efe-be3f-a32d9c67a9e8.png)
![image](https://user-images.githubusercontent.com/97974194/187953296-7370d174-b987-4ba0-b71a-a7b192d4e745.png)
i think its all info needed =] 
no i didnt ran pixelorama from terminal. i just cant cause i installed from flatpak lol

**Comment by Variable-ind** [comment]
It should be able to do it perhaps the extension list it's trying to download is to a folder That reqires sudo permission 🤔
Sadly I'm not on Arch and can't replicate this issue

**Comment by Variable-ind** [comment]
Perhaps it's cause you are using Flatpak (in the meantime you can download extensions like this https://github.com/Variable-ind/Pixelorama-Extensions#extensions-and-their-details

**Comment by hacknorris-aka-penguin** [comment]
so from where i'll know which extensions are listed ? means their which arent yours...

**Comment by Variable-ind** [comment]
plus you can run flatpak apps from terminal
e.g to run pixelorama i use command `flatpak run com.orama_interactive.Pixelorama`

**Comment by hacknorris-aka-penguin** [comment]
oh , so every app from flatpak is 100% offline app? thx for info =]

**Comment by Variable-ind** [comment]
you're welcome!, I'll close this issue now
